language: php

sudo: false

php:
  - "5.6"
  - "7"

matrix:
  include:
    - php: "5.6"
      env: CHECKSTYLE="YES" COVERAGE="YES"
  allow_failures:
    - php: "7"

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: ./vendor/bin/ci-runner
